include: package:effective_dart/analysis_options.1.2.0.yaml

linter:
  rules:
    public_member_api_docs: false
    directives_ordering: false
    prefer_initializing_formals: true
    type_annotate_public_apis: false