include: package:lint/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    directives_ordering: false
    prefer_initializing_formals: true
    type_annotate_public_apis: false
    avoid_print: false