name: WhatsAppClone
description: A Text Message WhatsApp Clone.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # state managment 
  stacked: ^1.7.6
  provider: ^4.3.2+1
  # inversion of control
  get_it: ^5.0.0
  # stacked
  stacked_services: ^0.5.4+4
  # device
  permission_handler: ^5.0.1+1
  contacts_service: ^0.4.6
  call_log: ^2.1.0
  # network
  connectivity: ^0.4.9+2
  flutter_dialogflow: ^0.1.3
  # firebase
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_analytics: ^6.0.0
  firebase_core: ^0.5.0
  # storage
  shared_preferences: ^0.5.10
  sqflite: ^1.3.1+1
  # helpers
  intl: ^0.16.1
  android_intent: ^0.3.7+3
  url_launcher: ^5.5.0
  fluttertoast: ^7.0.4
  # UI widets
  flutter_spinkit: ^4.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  effective_dart: ^1.2.0
  mockito:

flutter:

  uses-material-design: true

  assets:
     - asset/images/whatsapp_icon.png
     - asset/images/Whatsapp_Wallpaper.jpg
     - private/credentials.json
