name: WhatsAppClone
description: A Text Message WhatsApp Clone.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_intent: ^0.3.7+3
  call_log: ^2.1.0
  cloud_firestore: ^0.14.0+2
  connectivity: ^0.4.9+2
  contacts_service: ^0.4.6
  equatable: ^1.2.5
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_storage: ^4.0.1
  flutter_dialogflow: ^0.1.3
  flutter_spinkit: ^4.1.2
  fluttertoast: ^7.0.4
  get_it: ^5.0.0
  google_fonts: ^1.1.0
  image_picker: ^0.6.7+11
  intl: ^0.16.1
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+1
  rxdart: ^0.24.1
  shared_preferences: ^0.5.10
  sqflite: ^1.3.1+1
  stacked: ^1.7.6
  stacked_services: ^0.5.4+4
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0

  # icon generator
  flutter_launcher_icons: ^0.8.1
  # native splash generator
  flutter_native_splash: ^0.1.9
  mockito: null
  test: any

# flutter icons setup
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

# flutter splash screen setup
flutter_native_splash:
  image: assets/images/whatsapp_icon.png
  color: "#ffffff"
  android_disable_fullscreen: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/whatsapp_icon.png
    - assets/images/Whatsapp_Wallpaper.jpg
    - private/credentials.json
